@startuml

sprite $locked [16x16/16] {
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFF800008FFFFF
FFFF80000008FFFF
FFFF00FFFF00FFFF
FFFF00FFFF00FFFF
FFFF00FFFF00FFFF
FFFF00FFFF00FFFF
FFF0000000000FFF
FFF0000000000FFF
FFF0000880000FFF
FFF0000880000FFF
FFF0000880000FFF
FFF0000000000FFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
}

sprite $unlocked [61x16/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFF80008FFFFFFFFFFFFFFF80008FFFFFFFFFFFFFFFF000FFFFFFFFFFFFFF
FF8000008FFFFFFFFFFFFF8000008FFFFFFFFFFFFFF00000FFFFFFFFFFFFF
FF00FFF000000000000FFF00FFF000000000000FFF00FFF000000000000FF
FF00FFF000000000000FFF00FFF000000000000FFF00FFF000000000000FF
FF8000008FFFF00FF00FFF8000008FFFF000000FFFF00000FFFFF00FF00FF
FFF80008FFFFF00FF00FFFF80008FFFFF000000FFFFF000FFFFFF00FF00FF
FFFFFFFFFFFFF00FF00FFFFFFFFFFFFFF00FF00FFFFFFFFFFFFFF00FFFFFF
FFFFFFFFFFFFF00FF00FFFFFFFFFFFFFF00FF00FFFFFFFFFFFFFF00FFFFFF
FFFFFFFFFFFFF00FF00FFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFF00FFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}


[mqtt-stub] as mqtt
rectangle Provider <<$locked>>
rectangle Broker <<$unlocked>>
rectangle Parser <<$locked>>
rectangle "Consumer #1" <<$locked>> as c1
rectangle "Consumer #2" <<$locked>> as c2

mqtt -> Provider
Provider -> Broker : set
Broker <--> Parser : parse

c1 -[hidden]- c2
Broker <-c1 : get
Broker <-c2 : get

@enduml