# ntp config used on mac
pool 0.debian.pool.ntp.org iburst
pool 1.debian.pool.ntp.org iburst
pool 2.debian.pool.ntp.org iburst
pool 3.debian.pool.ntp.org iburst

interface listen ipv4 10.0.0.10
# tell NTP to work in offline mode after 10s without peers
tos orphan 15 orphanwait 10
